name: CICD using Git actions and herokuu

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut Moving code from github to VM
        uses: actions/checkout@v3
      - name: tree
        run: tree
      - name: cd temp
        run: cd temp
      - name: touch
        run : touch def.txt
      - name: tree
        run: tree


