name: CICD using Git actions and herokuu

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut Moving code from github to VM
        uses: actions/checkout@v3
      - name: tree
        run: tree
      - name: pwd
        run: pwd
      - name: cd Demoo
        run : cd Demoo |
              pwd
      - name: tree
        run: tree


