name: CICD using Git actions and herokuu

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut Moving code from github to VM
        uses: actions/checkout@v3
      - name: pwd | 
              tree
        run: cd Demoo | 
              tree
      - name: build and test
        run:  mvn clean install
      - name: pwd
        run:  tree

